apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployments
  namespace: notes-app
  labels:
    app: notes-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:

      - name: notes-app
        image: jhaempire/notes-app-kubeadm
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits :
            cpu: 200m
            memory: 225Mi  
        livenessProbe:
          httpGet:
            path: /
            port: 8000    


