apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: my-storage


#in this we are claiming the persistent volume we have created it makes our authority stamped on that volume 

