apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace : mysql
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-storage
  hostPath:
    path: /mnt/data  # Local path on the node


#what we are doing here we are taking a 1 gi of memory form our host system and adding
# them to our workflow wwe will claim it later on 

